FROM ubuntu:latest

MAINTAINER Sushain Nadagoundla <sushain.nadagoundla@sjsu.edu>

RUN 
	apt-get update && apt-get install -y apache2 && apt-get clean /

ENV 
 APACHE_RUN_USER www-data /
 APACHE_RUN_GROUP www-data / 
 APACHE_LOG_DIR /var/log/apache2 /

 EXPOSE 80

 CMD ["/usr/sbin/apache2", "-D", "FOREGROUND"]




